# packages
packz <- c(
	# "adegenet",
	# "ape",
	"ASMap",
	# "bedr",
	# "biganalytics",
	# "bigmemory",
	"biomod2",
	# "boot",
	"bookdown",
	# "car",
	"classInt",
	# "compiler",
	# "corrplot",
	"countrycode",
	# "cowplot",
	"data.table",
	# "detectRUNS",
	"dismo",
	"dplyr",
	"ecospat",
	# "EMMREML",
	"ENMTools",
	"ENMeval",
	# "genetics",
	"geodata",
	"GGally",
	"ggfortify",
	"ggpubr",
	"ggplot2",
	# "ggrepel",
	# "ggsn",
	"ggthemes",
	"gplots",
	# "grid",
	# "gridExtra",
	# "gsheet",
	"gtools",
	# "hierfstat",
	# "Hmisc",
	# "jsonlite",
	"kableExtra",
	"knitr",
	"landscapetools",
	"latticeExtra",
	# "LDheatmap",
	# "likert",
	# "LinkageMapView",
	# "lme4",
	"magrittr",
	"mapdata",
	"maptools",
	"maps",
	"multcompView",
	"rnoaa",
	"paletteer",
	"parallel",
	# "pegas",
	# "phyloseq",
	"plotly",
	"png",
	# "PopGenome",
	# "pophelper",
	# "qqman",
	# "qualtRics",
	# "radiator",
	"rangeBuilder",
	"raster",
	"rasterVis",
	"readr",
	"reshape2",
	"readxl",
	"rgdal",
	"rgbif",
	"rJava",
	"rnaturalearth",
	"rnaturalearthdata",
	# "scales",
	# "scatterplot3d",
	"maps",
	"scales",
	"scico",
	"sf",
	"sp",
	"spData",
	# "spDataLarge",
	"spThin",
	"stringr",
	# "superheat",
	# "svglite",
	# 'TeachingDemos',
	"tidyr",
	# "tidyverse",
	# "tmap",
	# "ratervar",
	# "rgbif",
	# "qwraps2",
	# "qqman",
	"usdm",
	# "vcd",
	# "vcfR",
	# "VennDiagram",
	"viridis",
	"xtable"
	# "waffle"
	
)

# thanks to [Vikram](https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/)

lapply(
	packz,
	FUN = function(x) {
		if (!require(x, character.only = TRUE)) {
			install.packages(x, dependencies = TRUE)
			library(x, character.only = TRUE)
		}
	}
)